### ISSUE TITLE
Can't resolve the reference 'UIKit.UIColor UIKit.UIColor::get_SystemBackground()'

### ISSUE THREAD

**Issue by thedee** [redth-org/BTProgressHUD#100]
The following error occurs when using version 1.4.0 or 1.5.0.  The error doesn't occur using 1.3.5.  When making a build for iOS it throws the following error:

MTOUCH : error MT2101: Can't resolve the reference 'UIKit.UIColor UIKit.UIColor::get_SystemBackground()', referenced from the method 'System.Void BigTed.ProgressHUD::SetOSSpecificLookAndFeel()'

**Comment by Cheesebaron** [comment]
What version of iOS are you targeting?

**Comment by thedee** [comment]
> What version of iOS are you targeting?

iOS Build
SDK Version > 11.4

Then the job that runs the build in AzureDevOps:
Operating System
macOS
11.6.8

**Comment by Cheesebaron** [comment]
Hmm interesting.

These versions are using Xamarin.Legacy.Sdk to build the Xamarin.iOS supporting version, but perhaps that is somehow broken.

Can you perhaps try build your App on macOS-12 and with the latest Xamarin tooling? Does it build and link locally when you build for a device?

**Comment by KennyDM** [comment]
@Cheesebaron I'm also facing the same issue, updating the build agent to macOS-12 didn't resolve it. Downgrading to 1.3.5 seems like the only workaround for now.

Any other ideas?

**Comment by KennyDM** [comment]
An update, managed to resolve the issue by building the iOS project with the following versions:

Mono 6_12_17, XCode 13.4.1,Xamarin.iOS 15.10

**Comment by thedee** [comment]
> Hmm interesting.
> 
> These versions are using Xamarin.Legacy.Sdk to build the Xamarin.iOS supporting version, but perhaps that is somehow broken.
> 
> Can you perhaps try build your App on macOS-12 and with the latest Xamarin tooling? Does it build and link locally when you build for a device?

@Cheesebaron  No, it did not work.  It also looks like @KennyDM also verified this.
