### ISSUE TITLE
Cutomization

### ISSUE THREAD

**Issue by jbouche-work** [redth-org/BTProgressHUD#106]
## 🚀 Feature Requests

Hi, I'm coming from ProgressHUD witch is not compatible with .Net 8.0 for iOS and now I use BTProgressHUD.
Can we have access to the customizations properties ?

### ✍️ Describe the feature

Before use BTProgressHUD I was using ProgressHUD and the next customization properties were available :
            ProgressHUD.Shared.HudBackgroundColour = An UIColor;
            ProgressHUD.Shared.HudFont = An UIFont;
            ProgressHUD.Shared.HudForegroundColor = An UIColor;
            ProgressHUD.Shared.TintColor = An UIColor;
            ProgressHUD.Shared.RingThickness = 3;

Thanks by advance.
Jérôme.

**Comment by Cheesebaron** [comment]
They are already available? https://github.com/redth-org/BTProgressHUD/blob/main/BTProgressHUD/ProgressHUD.cs#L111

**Comment by jbouche-work** [comment]
> They are already available? https://github.com/redth-org/BTProgressHUD/blob/main/BTProgressHUD/ProgressHUD.cs#L111

Hi, yes but I cannot access it from BTProgressHUD neither ProgressHUD on my project :(.

No access from AppDelegate => FinishedLaunching()

No one work :
        ProgressHUD.hud
	ProgressHUD.Sha
	ProgressHUD.Tint

        BTProgressHUD.hud
        BTProgressHUD.Sha
        BTProgressHUD.Tint

        BTProgressHUD.prog

Project :
TargetFramework : net8.0-ios
OutputType : Exe
SupportedOSPlatformVersion : 13.0
...

Jérôme.

**Comment by lufo88ita** [comment]
Hi, same request here.

In the past version of this library there are various _static_ property which we can set to customize the aspect of the progress, like the color of the spinner, the corner size etc.
Those are not available at the moment.

@Cheesebaron 
You indicate a set of non-static field and they are a sub-set of the original availables

**Comment by Cheesebaron** [comment]
I'll have a look at fixing this

**Comment by Cheesebaron** [comment]
@jbouche-work @lufo88ita please let me know what you think about the solution in PR #107 and if it acommodates your needs of customization.

**Comment by jbouche-work** [comment]
> @jbouche-work @lufo88ita please let me know what you think about the solution in PR #107 and if it acommodates your needs of customization.

Looks to be ok, but I did not see the TintColor ?

**Comment by lufo88ita** [comment]
> @jbouche-work @lufo88ita please let me know what you think about the solution in PR #107 and if it acommodates your needs of customization.

WOW! So fast! Thank you. 
Maybe I misread, but I don't see the ring color and corner radius properties.

Thanks a lot!

**Comment by jbouche-work** [comment]
> > @jbouche-work @lufo88ita please let me know what you think about the solution in PR #107 and if it acommodates your needs of customization.
> 
> WOW! So fast! Thank you. Maybe I misread, but I don't see the ring color and corner radius properties.
> 
> Thanks a lot!

I thing that the RingThickness is the corner radius.
Bu yes I dit not see the ring color :).

**Comment by Cheesebaron** [comment]
> > > @jbouche-work @lufo88ita please let me know what you think about the solution in PR #107 and if it acommodates your needs of customization.
> > 
> > 
> > WOW! So fast! Thank you. Maybe I misread, but I don't see the ring color and corner radius properties.
> > Thanks a lot!
> 
> I think that the RingThickness is the corner radius. But yes I dit not see the ring color :).

There is now a `HudCornerRadius` prop to controll the corner radius



> > @jbouche-work @lufo88ita please let me know what you think about the solution in PR #107 and if it acommodates your needs of customization.
> 
> Many thanks for your feedback ^^. Looks to be ok, but I did not see the TintColor ?

You will be able to use `HudImageTintColor` to tint images shown in hud and `RingColor` to change the color of the progress indicators.

Also added methods to reset the style if needed. Check the PR again, I've updated the sample too.

**Comment by jbouche-work** [comment]
Looks great for me.
How can I test the demo ?

**Comment by jbouche-work** [comment]
> Yes, the sample App is just a MAUI App targeting iOS. You can clone the branch and see how it looks.



> Yes, the sample App is just a MAUI App targeting iOS. You can clone the branch and see how it looks.

Hi, it's ok for me.
Thanks a lot :)

**Comment by Cheesebaron** [comment]
Cool, I will merge it and make a new release, thanks for the feedback.
