### ISSUE TITLE
Spinner with transparent background

### ISSUE THREAD

**Issue by acaliaro** [redth-org/BTProgressHUD#109]
I would like to have the spinner (with Show method) without the background. I try to set Clear color but the result is a black square behind the spinner

❓ Expected behavior
Only the spinner visible

🪜 Reproduction steps
ProgressHUDAppearance.HudBackgroundColor = UIColor.Clear;

🛠 Configuration
Used the demo in this repo
📦 Package Version:
2.1.0
📱 iOS Version:
17.3 iphone 12

**Comment by Cheesebaron** [comment]
I will have a look and see what can be done about this.

**Comment by acaliaro** [comment]
I know that is a OOT, but if you can take a look also to

                    ProgressHUDAppearance.RingRadius = 30f;

Because the ring is always the same size (I think this property is used to have a bigger spinner, correct?)

**Comment by Cheesebaron** [comment]
The RingRadius is for when you are showing determinate progress and changing its size works:

![image](https://github.com/redth-org/BTProgressHUD/assets/249719/80213036-5750-4483-8390-5c115782eb85)

You use the API: `BTProgressHUD.Show("Hello!", progress);` for this one.

**Comment by acaliaro** [comment]
> The RingRadius is for when you are showing determinate progress and changing its size works:
> 
> ![image](https://private-user-images.githubusercontent.com/249719/343036909-80213036-5750-4483-8390-5c115782eb85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTM5OTEsIm5iZiI6MTcxOTQ5MzY5MSwicGF0aCI6Ii8yNDk3MTkvMzQzMDM2OTA5LTgwMjEzMDM2LTU3NTAtNDQ4My04MzkwLTVjMTE1NzgyZWI4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMzA4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDk2ZTdjM2VjMDRmODdlODdiMTk0NDA5ODkwYTAyZmI1YTMyOGY5OTAyOGQ3M2Q5NWVkYzJlMjJlNGVhNjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QdV1kjBz5bfGadunXQKDU0aTQfrqIkqvuwzu52A7tCk)
> 
> You use the API: `BTProgressHUD.Show("Hello!", progress);` for this one.

Thanks @Cheesebaron it works! I have not understand about the ring size. It does not change if I use "Show" method? What should I use?

**Comment by acaliaro** [comment]
ok, I have understand about the "size". Is not possible to modify the size of the spinner also if progress is not used?

**Comment by Cheesebaron** [comment]
Yeah, it would need some extra code to modify its bounds, even so I am not sure if it would make the UIActivityIndicator bigger. Can you make a new issue for this describing the desired effect you want?
