### ISSUE TITLE
When the phone is in landscape the HUD is still displayed in portrait

### ISSUE THREAD

**Issue by JRosanowski** [redth-org/BTProgressHUD#113]
## 🐛 Bug Report
When the phone is in landscape the HUD is still displayed in portrait

### ❓ Expected behavior
The HUD will display in the orientation of the phone or iPad.

### 🪜 Reproduction steps
Display HUD in landscape oriented phone

### 🛠 Configuration

BTProgressHUD added via nuget

📦 **Package Version:** 2.1.1

📱 **iOS Version:** iPhone 16.7.1, iPad 17.7

**Comment by Cheesebaron** [comment]
Can you elaborate what you are seeing. Just tested this in the demo project in the repo and it seems fine to me?

https://github.com/user-attachments/assets/ed0c3091-6de3-4d88-b722-0776da1dc2d6

**Comment by JRosanowski** [comment]
I tried the demo app and see that it's working. I realised this may be something to do with us having a .Net iOS app with a mix of native and embedded Maui views rather than having a strictly Maui app.

**Comment by JRosanowski** [comment]
Looks like a problem with our app rather than the library
