### ISSUE TITLE
Spinner doesn't show in front of modal

### ISSUE THREAD

**Issue by christopherspence** [redth-org/BTProgressHUD#50]
Hello, I have a modalVC (form sheet) that calls BTProgressHUD.show(), and it shows up behind the modal. Any idea how to fix this? 

Thanks,
Chris

**Comment by jdausten97** [comment]
I have this issue. I don't have hope it'll get answered seeing how @christopherspence mentioned this almost 2 years ago :(

**Comment by Cheesebaron** [comment]
Added a modal sample in https://github.com/redth-org/BTProgressHUD/commit/68db5177328444047d933e14c3269f0085a74d53 seems to work just fine. Closing this one.
