### ISSUE TITLE
Loading spinner indicator is not vertical centered on iPhoneX

### ISSUE THREAD

**Issue by anthonybattel** [redth-org/BTProgressHUD#62]
Loading spinner indicator is not vertical centered on iPhoneX

**Comment by anthonybattel** [comment]
![capture d ecran 2017-12-07 a 12 34 15](https://user-images.githubusercontent.com/14542800/33713561-0257ceda-db4c-11e7-830a-ed4e0bf146ce.png)

**Comment by robert-sayers** [comment]
Hi,

I don't believe this is just related to iPhone X but i thing when building with Xcode 9 it has most of the hud and toasts misaligned.   I have raised my own issue about this.
