### ISSUE TITLE
Crash: Window.Level not normal

### ISSUE THREAD

**Issue by mh05** [redth-org/BTProgressHUD#66]
When you are truing to used the progress bar and your top level is not normal.The application will throw an system.null exception

Fix:

```
 var window = UIApplication.SharedApplication.Windows.FirstOrDefault();
                    if (window == null)
                        return;
                    window.WindowLevel = UIWindowLevel.Normal;
```

Could you please add this code in show methode

**Comment by Cheesebaron** [comment]
I don't believe that we should be modifying the Window level. That seems like an odd side-effect of showing a hud.
