### ISSUE TITLE
Using a lot of Memory on App

### ISSUE THREAD

**Issue by alberto65mx** [redth-org/BTProgressHUD#68]
I was profiling my Xamarin From App and I realize that the ProgressHUD takes a lot of memory. Is there any way to avoid this?

Xamarin Froms 3.1.0.5
Device iPad mini 11.4

![screen shot 2018-07-16 at 2 13 06 pm](https://user-images.githubusercontent.com/41307995/42784107-f3994f8a-8902-11e8-8d03-58ef0fb70da2.png)

**Comment by alberto65mx** [comment]
@Redth

**Comment by Cheesebaron** [comment]
12 MB for a static instance doesn't seem like much. Reopen if you still think this is an issue.
