### ISSUE TITLE
Doesn't supports .net standard 2.0

### ISSUE THREAD

**Issue by ashlar64** [redth-org/BTProgressHUD#70]
Hello,  
Any chance to add support for .net standard 2.0?

I have this issue:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package BTProgressHUD 1.2.0.2 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package BTProgressHUD 1.2.0.2 supports:
  - monotouch (MonoTouch,Version=v0.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)	app1	1

**Comment by beeradmoore** [comment]
Hey @ashlar64 , I believe BTProgressHUD should only be added to the iOS project which should be a xamarinios10 project.
