### ISSUE TITLE
Xamarin Forms : Acr userdialog loading indicator not showing in Center

### ISSUE THREAD

**Issue by vijaypalve** [redth-org/BTProgressHUD#71]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [x] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Microsoft Visual Studio Professional 2017 
Version 15.9.12
VisualStudio.15.Release/15.9.12+28307.665
Microsoft .NET Framework
Version 4.7.02556
Installed Version: Professional

Xamarin   4.12.3.83 (d15-9@23fa80172)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.30 (e0af99a34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.4.0.64 (9c8d8e0)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

## Version of ACR UserDialogs Library
Acr.UserDialogs - 7.0.4

## Expected Behaviour
UserDialogs always in the center of the device screen.

## Actual Behavior
Acr userdialog loading indicator not showing in Center.

## Code of Conduct
Please find the sample application and screen shot.
![IMG_1971](https://user-images.githubusercontent.com/14092016/59904309-cb2b7d00-9420-11e9-8b6f-ff200255b5e9.PNG)
[Loader.zip](https://github.com/aritchie/userdialogs/files/3313347/Loader.zip)

**Comment by Amaro96** [comment]
This is happening to me too

**Comment by beeradmoore** [comment]
I believe this was fixed with https://github.com/nicwise/BTProgressHUD/pull/69. The current BTProgressHUD never made it to nuget. 

I have a fork over [here](https://github.com/FourPi/BTProgressHUD), which has been published to nuget as [BTProgressHUD-Updated](https://www.nuget.org/packages/BTProgressHUD-updated/).

**Comment by ram-spurtree** [comment]
@vijaypalve , Have you got any turn around for the issue?

**Comment by Cheesebaron** [comment]
I haven't had time to look at this, but I can schedule a release of this library very soon. Will have a go at testing this issue was solved.

**Comment by khanh245** [comment]
How’d the testing go and when will you be releasing this?

**Comment by Cheesebaron** [comment]
@khanh245 it is out now.

**Comment by almultimidia** [comment]
CRIAR informativo de ‘Loading’
font: https://www.youtube.com/watch?v=o9rsNgRn0Ts  

Primeiro instale a biblioteca **Acr.UserDialogs**
No arquivo “MainActivity.cs” adicione a biblioteca conforme na imagem:

![image](https://user-images.githubusercontent.com/117390962/206705413-980bb9e2-48c2-4ec0-af95-3fc0f8dd2ada.png)
Se **using  Acr.UserDialogs;** ficar  sublinhado vermelho, acrescente **.Extended**, conforme na imagem.

Em baixo da linha **base.Oncreate....**  insira o comando **UserDialogs.Init(this);**

Na  MainPage.xalm crie  a  tag Button e  insira a propriedade **Clicked=”button_OnClicked”**

![image](https://user-images.githubusercontent.com/117390962/206705694-53e133e6-a052-45d3-9247-b15b30bd6159.png)

E na MainPage.xalm.cs insira:

private async void button_OnClicked(object sender, EventArgs e)
        {
            using(var dialog = UserDialogs.Instance.Loading("Carregando!"))
        {
                for (int i = 1; i <= 10; i++)
                {
                    await Task.Delay(2000);
                    dialog.PercentComplete = i * 10;
                }
            }

![image](https://user-images.githubusercontent.com/117390962/206705783-610f8049-1563-43ad-bb89-8dc037f6c84b.png)

**Comment by almultimidia** [comment]
CRIAR informativo de ‘Loading’
font: https://www.youtube.com/watch?v=o9rsNgRn0Ts  

Primeiro instale a biblioteca **Acr.UserDialogs**
No arquivo “MainActivity.cs” adicione a biblioteca conforme na imagem:

![image](https://user-images.githubusercontent.com/117390962/206705413-980bb9e2-48c2-4ec0-af95-3fc0f8dd2ada.png)
Se **using  Acr.UserDialogs;** ficar  sublinhado vermelho, acrescente **.Extended**, conforme na imagem.

Em baixo da linha **base.Oncreate....**  insira o comando **UserDialogs.Init(this);**

Na  MainPage.xalm crie  a  tag Button e  insira a propriedade **Clicked=”button_OnClicked”**

![image](https://user-images.githubusercontent.com/117390962/206705694-53e133e6-a052-45d3-9247-b15b30bd6159.png)

E na MainPage.xalm.cs insira:

private async void button_OnClicked(object sender, EventArgs e)
        {
            using(var dialog = UserDialogs.Instance.Loading("Carregando!"))
        {
                for (int i = 1; i <= 10; i++)
                {
                    await Task.Delay(2000);
                    dialog.PercentComplete = i * 10;
                }
            }

![image](https://user-images.githubusercontent.com/117390962/206705783-610f8049-1563-43ad-bb89-8dc037f6c84b.png)
