### ISSUE TITLE
Crashes on iOS 12 or older devices

### ISSUE THREAD

**Issue by AyonAB** [redth-org/BTProgressHUD#74]
## 🐛 Bug Report

Crashes on older iOS devices because of the use of iOS Semantic Colors (SystemBackgroundColor, LabelColor etc.). There should be a checking of iOS version. 

`Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: +[UIColor systemBackgroundColor]: unrecognized selector sent to class 0x11ac07ec0`

### Reproduction steps
Update to latest version, use ProgesssHUD and run on any iOS 12 or below simulator or device

### Configuration
Visual Studio for Mac
Xamarin.iOS

**Version:** 1.3.0

**Platform:** 
- [ ] :iphone: iOS

**Comment by Cheesebaron** [comment]
Ah! Sorry for that.

@AyonAB do you have time to fix it in a Pull Request?

**Comment by AyonAB** [comment]
Sure, can do that.

**Comment by Cheesebaron** [comment]
@AyonAB that would be much appreciated.

I guess we should check either if the selector is available or iOS version is met.

**Comment by AyonAB** [comment]
@Cheesebaron done. Review the PR when you can.

**Comment by Cheesebaron** [comment]
@AyonAB thanks! Will have a look!

**Comment by Cheesebaron** [comment]
I've made a new release 1.3.1 with your fix. Thanks again!
