### ISSUE TITLE
reviving old xmaring project; type BTProgressHUD exists in Acr.UserDialogs

### ISSUE THREAD

**Issue by Nathan187** [redth-org/BTProgressHUD#81]
## 🐛 Bug Report
 (thanks in advance for any help)
Trying to revive an older application that was compiling in the past.  The application no longer complies..specifically the iOS project

### Expected behavior

application should compile and run

### Reproduction steps
 no steps to reproduce.  errors is:  _/Users/n/Desktop/Source Code/eP2/mobile/iOS/Renderers/Page/BasePageRenderer.cs(17,17): Error CS0433: The type 'BTProgressHUD' exists in both 'Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'BTProgressHUD, Version=1.3.2.0, Culture=neutral, PublicKeyToken=null' (CS0433)_ 

### Configuration

**Version:** 1.x

Acr.UserDialogs (6.3.1)
BTProgressHUD (1.3.2)

offending code:
BTProgressHUD.ForceiOS6LookAndFeel = true;
BTProgressHUD.Show(null, -1F, ProgressHUD.MaskType.Clear);

**Platform:** 
- [x ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
Acr.UserDialogs 6.3.1 probably bundles BTProgressHUD. Upgrade to the latest version to use it with BTProgressHUD.

**Comment by Nathan187** [comment]
thank you cheesebaron...i just removed the BTProgressHUD library from the project.  Works fine now
