### ISSUE TITLE
Crash on iOS 15

### ISSUE THREAD

**Issue by nicobarengo** [redth-org/BTProgressHUD#84]
## 🐛 Bug Report

I have an app that im getting a lots of crash reports when the OS is updated to iOS 15.

`System.NullReferenceException: Object reference not set to an instance of an object.`

**Stack trace**
```
BigTed ProgressHUD.<DismissWorker>b__98_2 ()
Foundation NSActionDispatcher.Apply ()
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr,intptr,intptr,bool)
```

### Expected behavior
Not to crash

### Reproduction steps
I believe that this is happening when the app is launched to do the background fetch and when its done the app crashes.

### Configuration

**Version:** 1.3.3

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by BramFP** [comment]
Adding to this for additional information, we've also experienced some crashes on iOS 15 but haven't tracked down the root cause yet.

Ours originates from Acr.UserDialogs which incorporates BTProgressHUD and we've got a different stack trace though, but just dropping it in here in case it might help.

```
ProgressHUD.PositionHUD (Foundation.NSNotification notification)
ProgressHUD.ShowProgressWorker (System.Single progress, System.String status, BigTed.ProgressHUD+MaskType maskType, System.Boolean textOnly, BigTed.ProgressHUD+ToastPosition toastPosition, System.String cancelCaption, System.Action cancelCallback, System.Double timeoutMs, System.Boolean showContinuousProgress, UIKit.UIImage displayContinuousImage)
ProgressHUD+<>c__DisplayClass18_0.<Show>b__0 ()
NSActionDispatcher.Apply ()
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr,intptr,intptr,bool)
NSObject.InvokeOnMainThread (System.Action action)
ProgressHUD.Show (System.String status, System.Single progress, BigTed.ProgressHUD+MaskType maskType, System.Double timeoutMs)
BTProgressHUD.Show (System.String status, System.Single progress, BigTed.ProgressHUD+MaskType maskType)
ProgressDialog+<>c__DisplayClass17_0.<Refresh>b__0 ()
NSActionDispatcher.Apply ()
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr,intptr,intptr,bool)
NSObject.InvokeOnMainThread (System.Action action)
ProgressDialog.Refresh ()
ProgressDialog.Show ()
AbstractUserDialogs.Progress (Acr.UserDialogs.ProgressDialogConfig config)
AbstractUserDialogs.Loading (System.String title, System.Action onCancel, System.String cancelText, System.Boolean show, System.Nullable`1[T] maskType)
AbstractUserDialogs.ShowLoading (System.String title, System.Nullable`1[T] maskType)
```

**Comment by mjo151** [comment]
I am also seeing a crash on iOS 15 when building against Xcode 13. I believe the problem is the use of UIApplication.SharedApplication.KeyWindow in the BTProgressHUB library. This property is deprecated and appears to be null in some cases, even after calling Window.MakeKeyAndVisible.

**Comment by Cheesebaron** [comment]
Hmm, interesting. I think we have to use `UIApplication.SharedApplication.ConnectedScenes` to get the foreground and active scene.

**Comment by Cheesebaron** [comment]
Can someone in this thread grab the artifact from this build and test my fix? https://github.com/redth-org/BTProgressHUD/pull/85/checks?check_run_id=3788006258

**Comment by nicobarengo** [comment]
Downloaded and installed... it's very unpredictable the crash, so I will get back with the results 🤞🏻

**Comment by nicobarengo** [comment]
@Cheesebaron I can confirm that the issue is resolved with the the latest build.

**Comment by Cheesebaron** [comment]
OK, that is cool. Thanks for testing.

**Comment by Cheesebaron** [comment]
1.3.4 has been released on NuGet

**Comment by mjo151** [comment]
@Cheesebaron please let me know if you need any additional information to track down this issue.

**Comment by marcoburato** [comment]
@Cheesebaron This is still not quite fixed, unfortunately. I've been adding some logging to my app to figure out why `GetActiveWindow()` would return null.

Here's the output from a crash report.

This is the normal condition immediately before calling `BTProgressHUD.Show()`, which works fine:

    KeyWindow = <UIWindow: 0x10b510b10; frame = (0 0; 428 926); tintColor = UIExtendedSRGBColorSpace 0 0.588235 0.203922 1; gestureRecognizers = <NSArray: 0x283841380>; layer = <UIWindowLayer: 0x2838414d0>>
    Windows =
      <UIWindow: 0x10b510b10; frame = (0 0; 428 926); tintColor = UIExtendedSRGBColorSpace 0 0.588235 0.203922 1; gestureRecognizers = <NSArray: 0x283841380>; layer = <UIWindowLayer: 0x2838414d0>>
        IsKeyWindow = True
        Hidden = False
        WindowLevel = 0
    Scenes:
      <UIWindowScene: 0x104e12fb0; scene = <FBSScene: 0x281868600; identifier: sceneID:REDACTED>; persistentIdentifier = DEAEB509-D8BF-462C-9B07-15688ADF1DA8; activationState = UISceneActivationStateForegroundActive; settingsScene = <UIWindowScene: 0x104e12fb0>; windows = (
        "<UIWindow: 0x10b510b10; frame = (0 0; 428 926); tintColor = UIExtendedSRGBColorSpace 0 0.588235 0.203922 1; gestureRecognizers = <NSArray: 0x283841380>; layer = <UIWindowLayer: 0x2838414d0>>"
      )>
        Windows =
          <UIWindow: 0x10b510b10; frame = (0 0; 428 926); tintColor = UIExtendedSRGBColorSpace 0 0.588235 0.203922 1; gestureRecognizers = <NSArray: 0x283841380>; layer = <UIWindowLayer: 0x2838414d0>>
            IsKeyWindow = True
            Hidden = False
            WindowLevel = 0
    ApplicationState = Active

This is the condition that causes the crash instead:

    KeyWindow = 
    Windows =
      <UIWindow: 0x10b510b10; frame = (0 0; 428 926); tintColor = UIExtendedSRGBColorSpace 0 0.588235 0.203922 1; gestureRecognizers = <NSArray: 0x283841380>; layer = <UIWindowLayer: 0x2838414d0>>
        IsKeyWindow = False
        Hidden = False
        WindowLevel = 0
    Scenes:
      <UIWindowScene: 0x104d18db0; scene = <FBSScene: 0x281855380; identifier: sceneID:REDACTED>; persistentIdentifier = DEAEB509-D8BF-462C-9B07-15688ADF1DA8; activationState = UISceneActivationStateForegroundInactive; settingsScene = <UIWindowScene: 0x104d18db0>; windows = (
        "<UIWindow: 0x10b510b10; frame = (0 0; 428 926); tintColor = UIExtendedSRGBColorSpace 0 0.588235 0.203922 1; gestureRecognizers = <NSArray: 0x283841380>; layer = <UIWindowLayer: 0x2838414d0>>"
      )>
        Windows =
          <UIWindow: 0x10b510b10; frame = (0 0; 428 926); tintColor = UIExtendedSRGBColorSpace 0 0.588235 0.203922 1; gestureRecognizers = <NSArray: 0x283841380>; layer = <UIWindowLayer: 0x2838414d0>>
            IsKeyWindow = False
            Hidden = False
            WindowLevel = 0
    ApplicationState = Inactive

Apparently, sometimes there is no KeyWindow and `UIApplication.SharedApplication.ApplicationState == Inactive`.

I'm not sure what the proper fix would be.
My app, like most others, only uses a single window. So, it's easy to just pick the only existing one.
In case of multiple windows, things are not so obvious. Perhaps in that use case it would make more sense to not use the convenience static methods and instead manually creating the ProgressHud with a new constructor that allows to specify the target window.

**Comment by marcoburato** [comment]
@Cheesebaron Can you reopen this issue based on my last comment? Or should I create a new one?

**Comment by devology-rob** [comment]
Hi, I'm also experiencing this crash on iOS 15 intermittently.  I'm using BTProgressHud 1.3.5 and the Xamarin crash is...

```
MyProject 2022-05-04T22:10:59Z  UI  1 - IosPlatformDifferences - Display Message 'The pin does not match'

2022-05-04 23:11:06.324 MyProject.iOS[16396:1424514] [AppCenterCrashes] ERROR: +[MSACWrapperLogger MSACWrapperLog:tag:level:]/10 Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at BigTed.ProgressHUD.PositionHUD (Foundation.NSNotification notification) [0x000cf] in /_/BTProgressHUD/ProgressHUD.cs:872 
  at Foundation.InternalNSNotificationHandler.Post (Foundation.NSNotification s) [0x00000] in /Users/builder/azdo/_work/2/s/xamarin-macios/src/Foundation/NSNotificationCenter.cs:48 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00013] in /Users/builder/azdo/_work/2/s/xamarin-macios/src/UIKit/UIApplication.cs:75 
  at MyProject.iOS.Application.Main (System.String[] args) [0x00001] in /Users/rob/GitHub/hillingar-MyProject-appv2/app/MyProject/MyProject.iOS/Main.cs:16 

2022-05-04 23:11:06.341 MyProject.iOS[16396:1424514] Unhandled managed exception: Object reference not set to an instance of an object (System.NullReferenceException)
  at BigTed.ProgressHUD.PositionHUD (Foundation.NSNotification notification) [0x000cf] in /_/BTProgressHUD/ProgressHUD.cs:872 
  at Foundation.InternalNSNotificationHandler.Post (Foundation.NSNotification s) [0x00000] in /Users/builder/azdo/_work/2/s/xamarin-macios/src/Foundation/NSNotificationCenter.cs:48 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00013] in /Users/builder/azdo/_work/2/s/xamarin-macios/src/UIKit/UIApplication.cs:75 
  at MyProject.iOS.Application.Main (System.String[] args) [0x00001] in /Users/rob/GitHub/hillingar-MyProject-appv2/app/MyProject/MyProject.iOS/Main.cs:16 
```

**Comment by brunck** [comment]
@devology-rob you should open a new issue for this since this one is closed.

**Comment by devology-rob** [comment]
> @devology-rob you should open a new issue for this since this one is closed.

Thanks, I noticed afterwards and created #95 and it already looks like you may have fixed it 👏
