### ISSUE TITLE
Release 1.3.4 seems to break Acr.UserDialogs

### ISSUE THREAD

**Issue by marcellorutter** [redth-org/BTProgressHUD#87]
## 🐛 Bug Report
Hello everybody.

Not sure about this bug but I'm going to open this issue just in the case someone else incurs in the same problem. Moreover, as you can read below, may be that the issue is related to Acr.UserDialogs but because of that project is on lockdown, it would help me to know if the compatibility between the twos may be restored.

It looks like that after updating BTProgressHUD from v. 1.3.3. to v. 1.3.4 in a project that also is using Acr.UserDialogs (last version 7.1.0.514 - this project is on lockdown), an exception is thrown when invoking method Acr.UserDialogs.IUserDialogs.ShowLoading(string).

Unfortunately, inspecting the exception does not help: there is no stack trace and the exception message is "Unable to load type."

PLEASE NOTE: I'm still investigating this issue and I will be back in case of new information and tests.

### ❓ Expected behavior
Calling Acr.UserDialogs.IUserDialogs.ShowLoading(string) should display a waiting dialog.

### Reproduction steps
None in particular. This behavior happens always, as far as I call ShowLoading(string).

📦 **Package Version: 1.3.4**
Reverting BTProgressHUD to v. 1.3.3 solves the issue.

📱 **iOS Version: Simulator, v. 14.5**

**Comment by Cheesebaron** [comment]
Don't worry about it @aritchie. Stack trace ends in BTProgressHUD, so it must be the culprit, right? 😏 

@mrutter can you confirm the newer version of Acr.UserDialogs fixes your issue?
